apiVersion: v1
kind: Namespace
metadata:
  name: gitops-controller
  labels:
    system: "true"
    operator: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-controller
  namespace: gitops-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: gitops-controller
  namespace: gitops-controller
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gitops-controller
  namespace: gitops-controller
  labels:
    app: gitops-controller
spec:
  selector:
    matchLabels:
      app: gitops-controller
  template:
    metadata:
      labels:
        app: gitops-controller
    spec:
      serviceAccountName: gitops-controller
      containers:
      - image: justinbarrick/gitops-controller:0.1.1
        imagePullPolicy: Always
        name: gitops-controller
        resources:
          limits:
            memory: "512Mi"
            cpu: "100m"
          requests:
            memory: "256Mi"
            cpu: "50m"
        env:
        - name: SSH_KEY_PATH
          value: /ssh/identity
        volumeMounts:
        - name: git-ssh
          readOnly: true
          mountPath: /ssh/identity
          subPath: identity
        - name: gitops-config
          readOnly: true
          mountPath: /config.yaml
          subPath: config.yaml
      volumes:
      - name: git-ssh
        secret:
          secretName: git-ssh
          defaultMode: 0600
      - name: gitops-config
        configMap:
          name: gitops-controller
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-controller
  namespace: gitops-controller
data:
  config.yaml: |
    gitUrl: git@github.com:justinbarrick/git-controller-test.git
    gitPath: .
    rules:
    - apiGroups:
      - snapshot.storage.k8s.io
      resources: 
      - volumesnapshots
      - volumesnapshotcontents
      syncTo: git
---
